name: pdb-prepare-wizard
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - biopython
  - plip
  - matplotlib
  - seaborn
  - jupyter
  - pip
  - pip:
    - plip
    - openpyxl>=3.0.0 